routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('/products', 'ProductsController');
Route::get('/testpro', function () {
   return view('frontend.cart.checkout');
});
Route::get('/monitorh2h', function () {
   return view('frontend.include.komodo');
});
Route::get('/invoice-info', function () {
   return view('frontend.transaction.invoice_info');
});
Route::get('/ask/{id}', function ($id) {
   return view('frontend.discussion',compact('id'));
});
Route::get('/stats', 'BackendController@getStats');
Route::get('/maintenance', function () {
   return view('maintenance');
});
// Auth::routes();
Route::resource('category', 'CategoryController', [
    'except' => ['show'],
    'names' => 'admin.category'
  ]);
Route::any('/getongkir', 'FrontendController@ongkir');
Route::get('/getCity', 'FrontendController@getCity');
Route::get('/getDistrict', 'FrontendController@getDistrict');
Route::post('/addVideo', 'ProductsController@uploadVideo')->name('products.add.video');
//Route::get('/home', 'HomeController@index');
Route::get('/empty-cart/{id}', 'CartController@destroy');
/* Frontend part of the shop */
Route::get('/', 'FrontendController@home');
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
 Route::get('/{provider}/callback', 'Auth\AuthController@handleProviderCallback');
Route::get('/home', 'FrontendController@home');
Route::get('/collection', 'FrontendController@collection')->name('frontend.collection');
//Route::get('/collection', 'FrontendController@collection');
Route::get('/topbrands', 'FrontendController@topbrands');
//Route::get('/cart', 'FrontendController@cart');
Route::get('/contact', 'FrontendController@contact');
Route::post('/attempt', 'FrontendController@attempt');
Route::post('/postDiscuss', 'FrontendController@storeDiscuss');
Route::post('/postQuestion', 'FrontendController@storeQuestion');
Route::get('/filter', 'FrontendController@filter');
Route::get('/login', 'FrontendController@login');
Route::get('/signin', 'FrontendController@signin');
Route::get('/signup', 'FrontendController@signup');
Route::get('/vendor-signup', 'FrontendController@vendorSignup');
Route::post('/registration', 'FrontendController@process_vendorSignup');
Route::get('/user/activation/{token}', 'Auth\RegisterController@userActivation');
Route::post('/process_signin', 'FrontendController@create');
Route::post('/search', 'FrontendController@search')->name('frontend.search');
Route::get('/details/{id}', 'FrontendController@details')->name('frontend.detail');
// Route::get('/category/{id}', 'FrontendController@show')->name('collection.show');
Route::get('/category/{id}', 'FrontendController@subproduct')->name('collection.subproduct');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/buynow/{id}', 'CartController@buynow')->name('cart.buy');

Route::get('shop/{id}', 'MerchantController@detail')->name('merchant.detail');

Route::resource('/cart', 'CartController');
Route::any('/update/qty', 'CartController@updateQty')->name('update.qty');
Route::resource('/address', 'AddressController');
Route::get('/checkout', 'CheckoutController@checkout')->name('frontend.checkout');
//Route::get('/checkout', 'CheckoutController@step1');


Route::get('/viewcheckout', 'FrontendController@checkout');



Route::post('/checkout', 'CheckoutController@checkout')->name('checkout');
//Route::get('/checkout', 'CheckoutController@step1');

Route::get('/snap', 'SnapController@snap');
Route::get('/delete/{id}', 'CartController@destroy');
Route::post('/snaptoken', 'SnapController@token');
Route::post('/snapfinish', 'SnapController@finish');

Route::get('/ivoucher', 'FrontendController@ivoucher')->name('frontend.ivoucher');
Route::get('/tracking', 'FrontendController@tracking')->name('frontend.tracking');

Route::group(['middleware' => 'auth'], function () {

    Route::get('shipping-info', 'CheckoutController@shipping')->name('checkout.shipping');
    Route::get('/payment', 'CheckoutController@payment')->name('checkout.payment');
    Route::post('/store-payment', 'CheckoutController@storePayment')->name('payment.store');

    Route::get('/biodata', 'FrontendController@biodata')->name('frontend.biodata');
    Route::get('/penjualan', 'FrontendController@penjualan')->name('frontend.penjualan');
    Route::get('/pembelian', 'TransactionController@pembelian')->name('frontend.pembelian');
    Route::get('/pembelian/{mode}', 'TransactionController@pembelian')->name('frontend.pembelian');
    Route::get('/my/sales', 'TransactionController@mySales')->name('frontend.mySales');
    Route::get('/list/sales/{id}', 'TransactionController@sales')->name('frontend.salesConfirmation');
    Route::post('/update/profile', 'FrontendController@profile')->name('frontend.profile');
    Route::get('/alamat', 'AddressController@alamat')->name('frontend.alamat');
    Route::post('/alamat/detail', 'AddressController@alamatDetail')->name('address.alamatDetail');
    Route::get('/alamat/delete/{id}', 'AddressController@delete')->name('address.delete');
    Route::post('/store', 'AddressController@store')->name('address.store');
    Route::post('/alamat/update', 'AddressController@update')->name('address.update');
    Route::post('/alamat/delete/{id}', 'AddressController@destroy')->name('address.destroy');
    Route::get('/discussion', 'FrontendController@discussion')->name('frontend.diskusi');
    Route::get('/discussion/{id}', 'FrontendController@discussionAkun')->name('frontend.akun');

    Route::get('/create/merchant', 'FrontendController@create_merchant')->name('frontend.create_merchant');
    Route::get('/create/step', 'FrontendController@cretae_step')->name('frontend.step');
    Route::post('/add/merchant', 'MerchantController@create')->name('merchant.add');
    Route::post('/add/merchant/step', 'MerchantController@createStep')->name('merchant.step');
    Route::get('/my/merchant/{id}', 'FrontendController@myMerchant')->name('merchant.my');
    Route::post('/merchant/{id}/edit', 'MerchantController@edit')->name('merchant.edit');
    Route::get('/shop/update/{id}', 'FrontendController@merchantUpdate')->name('merchant.update');
    Route::get('/merchant/detail', 'FrontendController@merchantDetail')->name('merchant.detail');
    Route::get('/merchant/confirmation/resi', 'FrontendController@merchantConfirmationResi')->name('merchant.confirmation');


    Route::get('/trx/sales', 'OrdersController@trxSales')->name('sales.trx');
    Route::get('/acceptOrder', 'TransactionController@transactionUpdate');
    Route::get('/denyOrder', 'TransactionController@transactionUpdate');

    //products
    Route::get('/products/add/image', 'FrontendController@productAddImage')->name('product.image');
    Route::get('/products/add/video', 'FrontendController@productAddVid')->name('product.video');
    Route::get('/products/edit/video', 'FrontendController@productEdit')->name('product.edit_video');
    Route::get('/products/choose', 'FrontendController@chooseMethod')->name('product.choose');
    Route::post('/reset/password', 'FrontendController@resetPassword')->name('profile.reset');
    Route::post('/address/change', 'AddressController@addressChange')->name('address.change');

    //my transaction
    Route::get('/trx/invoice', 'TransactionController@trxMetode');
    Route::get('/order/detail/{id}', 'OrdersController@orderDetail');
    Route::get('/trx/paymentguide', 'TransactionController@trxGuide');
    Route::any('/getguide/{id}', 'FrontendController@getGuide')->name('get.guide');
    Route::any('/trx/detail', 'TransactionController@trxDetail')->name('trx.detail');
    Route::any('/trx/detail/product', 'TransactionController@trxDetailProduct')->name('trx.detailProduct');
//    Route::get('logout', 'BackendController@getLogout')->name('frontend.signin');

    Route::get('/reservasi', 'FrontendController@reservasi');
});


    /* Backend part of the shop */
Route::get('/admin', 'BackendController@admin');


/* Admin resource controller */
Route::resource('/categories', 'CategoryController');
Route::resource('/brands', 'BrandsController');
Route::resource('/products', 'ProductsController');

Route::get('/merchant/', 'MerchantController@getMerchant');
Route::get('/merchant/{id}', 'MerchantController@detailAssigment')->name('admin.merchant.detail');
Route::post('/approveMerchant', 'MerchantController@approveShop');
Route::post('toggledeliver/{orderId}', 'OrdersController@toggledeliver')->name('toggle.deliver');
Route::resource('/attribute', 'AttributeController');
Route::resource('/attribute_set', 'AttributeSetController');
Route::get('menu/sort/{type}', 'MenuController@sort_form')->name('admin.menu.sort_form');
  Route::post('menu/sort/{type}', 'MenuController@sort')->name('admin.menu.sort');
  Route::resource('menu', 'MenuController', [
    'names' => 'admin.menu'
  ]);
Route::delete('page/bulkdelete', 'PageController@bulkdelete')->name('admin.page.bulkdelete');
  Route::get('page/search/{query?}', 'PageController@search')->name('admin.page.search');
  Route::resource('page', 'PageController', [
    'names' => 'admin.page'
  ]);
  Route::get('get_parent_menu.json', 'MenuController@parent_menu')->name('admin.menu.parent.json');
  Route::get('get_child_menu.json', 'MenuController@child_menu')->name('admin.menu.child.json');
  Route::get('get_type_menu.json', 'MenuController@type')->name('admin.menu.type');


Route::get('/users/{type?}', [
    'uses' => 'UsersController@index',
    'as' => 'users',
    'middleware' => 'roles',
    'roles' => ['Admin']
    ]);
Route::get('/manage_users', [
    'uses' => 'UsersController@manage_users',
    'as' => 'manage_users',
    'middleware' => 'roles',

resources/views/frontend/layouts/layout_home.blade.php
<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <title>
      @yield('title')
    </title>
    <meta charset="UTF-8">
    @yield('someCSS')

    @include('frontend.include.css')
</head>
<body>
  <div class="super_container">
    @include('frontend.include.header_page')
    @yield('content')

    @include('frontend.include.footer_page')
  </div>


  

  <script src="{{asset('js/jquery-3.3.1.min.js')}}"></script>
  <script src="{{asset('styles/bootstrap4/popper.js')}}"></script>
  <script src="{{asset('styles/bootstrap4/bootstrap.min.js')}}"></script>
  <script src="{{asset('plugins/greensock/TweenMax.min.js')}}"></script>
  <script src="{{asset('plugins/greensock/TimelineMax.min.js')}}"></script>
  <script src="{{asset('plugins/scrollmagic/ScrollMagic.min.js')}}"></script>
  <script src="{{asset('plugins/greensock/animation.gsap.min.js')}}"></script>
  <script src="{{asset('plugins/greensock/ScrollToPlugin.min.js')}}"></script>
  <script src="{{asset('plugins/OwlCarousel2-2.2.1/owl.carousel.js')}}"></script>
  <script src="{{asset('plugins/slick-1.8.0/slick.js')}}"></script>
  <script src="{{asset('plugins/easing/easing.js')}}"></script>
  <script src="{{asset('js/custom.js?version=1')}}"></script>
@yield('someJS')
</body>

</html>

resources/views/frontend/layouts/layout_profile.blade.php
@extends('frontend.layouts.layout_page')

@section('someCSS')
  <link rel="stylesheet" type="text/css" href="{{asset('styles/cart_styles.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('styles/cart_responsive.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('styles/product_styles.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('styles/contact_styles.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('styles/contact_responsive.css')}}">

  <style>
    .cart_item_name {
      margin-left: 0%;
    }
    .alamat_name {
      font-size: 12px;
      font-weight: 500;
      color: rgba(0, 0, 0, 0.82);
    }
    .alamat_location {
      font-size: 12px;
      font-weight: 400;
      color: rgba(0,0,0,0.5);
    }
    .telp_padding{
      padding-top: 15px;
    }
    .float_right{
      float: right;
    }
    .cart_padding {
        padding-right: 15px;
    }
    .width_100{
        width: 100%;
    }
    .margin_0{
      margin-top: 0px;
    }
    .cart_button_checkout{
      font-size: 14px;
    }
    .cart_item_image {
      width: 65px;
      height: 65px;
      margin-right: 10px;
    }
    .price{
      font-size: 15px;
      color: #0e8ce4;
    }
    .qty{
      font-size: 12px;
      font-weight: 400;
    }
    .name{
      font-size: 13px;
    }
    .no_padding{
      padding-left: 0px;
      padding-right: 0px;
      padding-top: 10px;
    }
    .list-dropdown{
      padding-left: 5px;
      padding-right: 5px;
    }
    .menu-dropdown{
      font-size: 12px;
    }
    .padding-top-10{
      padding-top: 10px;
    }
    .order_total_title{
      line-height: 25px;
    }
    .order_total_amount{
      line-height: 25px;
    }
    .margin-left-0{
        margin-left: 0px;
    }
    .padding-top-30{
      padding-top: 30px;
    }
    .margin-top-15{
      margin-top: 15px;
    }

    .shop_sidebar {
        width: auto;
        transform: translateX(0px);
    }
    .sidebar_categories {
        margin-top: 0px;
    }
    .list-name{
      font-weight: 500;
      font-size: 15px;
      color: #0e8ce4;\;
    }
    .margin-top-botton-10{
      margin-top: 10px;
      margin-bottom: 10px;
    }
    .cart_item_title{
      font-weight: 500;
      font-size: 16px;
      color: rgb(14, 140, 228);
    }
    .cart_items {
      margin-top: 39px;
    }
    .name-title {
      color: #727577;
      margin-bottom: 10px;
    }
    .btn-foto{
      background: #b5b6b7ed;
    }
    .desc-foto{
      font-size: 11px;
      line-height: 1.4;
    }
  	.hover-active{
  		color: black !important;
  	}
    .cart_item{
      padding-right: 0px;
      padding: 15px !important;
    }
    .btn-toko{
      width: 100%;
      margin-bottom: 10px;
      text-align: center;
    }
    .list-name{
      margin-bottom: 0px;
    }
  </style>
  @yield('css')
@endsection

@section('someJS')
  <script src="{{asset('js/product_custom.js')}}"></script>
@endsection

@section('content')
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="cart_container">
            <div class="row col-md-12">
              <div class="col-md-3">
                <div class="cart_items">
                  <ul class="cart_list">
                    <li class="cart_item clearfix">
                      <div class="d-flex flex-md-row flex-column justify-content-between">
                        <div class="cart_item_name cart_info_col width_100 padding-top-10">
                          <div class="shop_sidebar">
                						<div class="sidebar_section">
                              @if(empty(App\Shop::whereUserId(Auth::user()->id)->first()))
                                <a href="{{ url('create/merchant') }}" class="button cart_button_checkout btn-toko">Buat Merchant</a>
                              @endif
                              <p class="list-name margin-top-botton-10 list-name">Profile Saya</p>
                							<ul class="sidebar_categories">
                								<li><a href="{{ url('/biodata') }}" class="@yield('biodata')">Biodata Diri</a></li>
                  							<li><a href="{{ url('/alamat') }}" class="@yield('alamat')">Alamat</a></li>
                  							<li><a href="{{ url('/tracking') }}" class="@yield('tracking')">Tracking</a></li>
                							</ul>
                              <p class="list-name list-name margin-top-botton-10">Kotak Masuk</p>
                              <ul class="sidebar_categories">
                                <li><a href="#" class="@yield('pesan')">Pesan</a></li>
                                <li><a href="{{ route('frontend.diskusi') }}" class="@yield('diskusi')">Diskusi</a></li>
                              </ul>
                              <p class="list-name margin-top-botton-10">Transaksi Saya</p>
                							<ul class="sidebar_categories">
                								<!--<li><a href="#" class="@yield('pending_pay')">Menunggu Pembayaran</a></li>!-->
                								<li><a href="{{ url('/pembelian') }}" class="@yield('daftar_trx')">Pembelian
                                  @if(\App\Orders::where('user_id', \Auth::user()->id)->where('payment_status','!=','done')->count())
                                  <span class="badge badge-primary">{{count(\App\Orders::where('user_id', \Auth::user()->id)->where('payment_status', '!=', 'done')->where('payment_status', '!=', 'expired')->get())}}</span>
                                  @endif
                                  </a>
                                </li>
                                @if(App\Shop::whereUserId(Auth::user()->id)->first())
                                  @php
                                  $user = \Auth::user();
                                  $orders = \App\Orders::whereHas('orderItems', function ($query) use ($user) {
                                              $query->where('shop_id', '=', $user->id);

                                          })->with('orderItems')->where('payment_status', '=', 'settlement')->get();

                                          @endphp
                                @endif
                							</ul>
                              @if(App\Shop::whereUserId(Auth::user()->id)->first())
                                @if(App\Shop::whereUserId(Auth::user()->id)->first()->status == '1')
                                  <p class="list-name list-name margin-top-botton-10">Merchant</p>
                                  <ul class="sidebar_categories">
                                      <li><a href="{{ url('/my/sales') }}" class="@yield('sold')">Penjualan
                                        @if(count($orders) !== 0)
                                        <span class="badge badge-primary">{{count($orders)}}</span>
                                        @endif
                                        </a>
                                      </li>
                                      <li><a href="{{ route('merchant.my', [App\Shop::whereUserId(Auth::user()->id)->first()->shop_slug]) }}" class="@yield('my_merchant')">My Merchant</a></li>
                                      <li><a href="{{ route('products.create') }}" class="@yield('product_add')">Tambah Produk</a></li>
                                      <li><a href="{{ url('products') }}" class="@yield('product')">Daftar Produk</a></li>
                                      <!-- <li><a href="#" class="@yield('ulasan')">Produk Terjual</a></li> -->
                                    </ul>
                                @else
                                  <p class="list-name list-name margin-top-botton-10">Merchant</p>
                                  <ul class="sidebar_categories">
                                    <li><span class="button cart_button_checkout" style="background:#ff9207d4;">Menunggu Konfirmasi</span></li>
                                  </ul>
                                @endif
                              @endif
                						</div>
                					</div>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-md-9">
                <div class="cart_items">
                  <ul class="cart_list">
                    <li class="cart_item clearfix cart_padding">
                      @yield('content_div')
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
@endsection

resources/views/frontend/layouts/layout_seller.blade.php
@extends('frontend.layout_seller_page')

@section('someCSS')
  <link rel="stylesheet" type="text/css" href="{{asset('styles/cart_styles.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('styles/cart_responsive.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('styles/product_styles.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('styles/contact_styles.css')}}">
  <link rel="stylesheet" type="text/css" href="{{asset('styles/contact_responsive.css')}}">

  <style>
    .cart_item_name {
      margin-left: 0%;
    }
    .alamat_name {
      font-size: 12px;
      font-weight: 500;
      color: rgba(0, 0, 0, 0.82);
    }
    .alamat_location {
      font-size: 12px;
      font-weight: 400;
      color: rgba(0,0,0,0.5);
    }
    .telp_padding{
      padding-top: 15px;
    }
    .float_right{
      float: right;
    }
    .cart_padding {
        padding-right: 15px;
    }
    .width_100{
        width: 100%;
    }
    .margin_0{
      margin-top: 0px;
    }
    .cart_button_checkout{
      font-size: 14px;
    }
    .cart_item_image {
      width: 65px;
      height: 65px;
      margin-right: 10px;
    }
    .price{
      font-size: 15px;
      color: #0e8ce4;
    }
    .qty{
      font-size: 12px;
      font-weight: 400;
    }
    .name{
      font-size: 13px;
    }
    .no_padding{
      padding-left: 0px;
      padding-right: 0px;
      padding-top: 10px;
    }
    .list-dropdown{
      padding-left: 5px;
      padding-right: 5px;
    }
    .menu-dropdown{
      font-size: 12px;
    }
    .padding-top-10{
      padding-top: 10px;
    }
    .order_total_title{
      line-height: 25px;
    }
    .order_total_amount{
      line-height: 25px;
    }
    .margin-left-0{
        margin-left: 0px;
    }
    .padding-top-30{
      padding-top: 30px;
    }
    .margin-top-15{
      margin-top: 15px;
    }

    .shop_sidebar {
        width: auto;
        transform: translateX(0px);
    }
    .sidebar_categories {
        margin-top: 0px;
    }
    .list-name{
      font-weight: 500;
      font-size: 15px;
      color: #0e8ce4;\;
    }
    .margin-top-botton-10{
      margin-top: 10px;
      margin-bottom: 10px;
    }
    .cart_item_title{
      font-weight: 500;
      font-size: 16px;
      color: rgb(14, 140, 228);
    }
    .cart_items {
      margin-top: 39px;
    }
    .name-title {
      color: #727577;
      margin-bottom: 10px;
    }
    .btn-foto{
      background: #b5b6b7ed;
    }
    .desc-foto{
      font-size: 11px;
      line-height: 1.4;
    }
  	.hover-active{
  		color: #0e8ce4 !important;
  	}
    .cart_item{
      padding-right: 0px;
      padding: 15px !important;
    }
    .btn-toko{
      width: 100%;
      margin-bottom: 10px;
      text-align: center;
    }
  </style>
  @yield('css')
@endsection

@section('someJS')
  <script src="{{asset('js/product_custom.js')}}"></script>
@endsection

@section('content')
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="cart_container">
            <div class="row col-md-12">
              <div class="col-md-3">
                <div class="cart_items">
                  <ul class="cart_list">
                    <li class="cart_item clearfix">
                      <div class="d-flex flex-md-row flex-column justify-content-between">
                        <div class="cart_item_name cart_info_col width_100 padding-top-10">
                          <div class="shop_sidebar">
                            <div class="sidebar_section">
                              @if(empty(App\Shop::whereUserId(Auth::user()->id)->first()))
                                <a href="{{ url('create/merchant') }}" class="button cart_button_checkout btn-toko">Buat Merchant</a>
                              @endif
                              <p class="list-name">Kotak Masuk</p>
                              <ul class="sidebar_categories">
                                <li><a href="#" class="@yield('diskusi')">Diskusi</a></li>
                                <li><a href="#" class="@yield('ulasan')">Ulasan</a></li>
                              </ul>
                              <p class="list-name">Toko Saya</p>
                              <ul class="sidebar_categories">
                              @if(App\Shop::whereUserId(Auth::user()->id)->first())
                                @if(App\Shop::whereUserId(Auth::user()->id)->first()->status == '1')
                                    <li><a href="{{ route('products.create') }}" class="@yield('product_add')">Jual Barang</a></li>
                                    <li><a href="{{ url('products') }}" class="@yield('product')">Daftar Barang</a></li>
                                    <li><a href="#" class="@yield('ulasan')">Barang Terjual</a></li>
                                @else
                                    <li><span class="button cart_button_checkout" style="background:#ff9207d4;">Menunggu Konfirmasi</span></li>
                                @endif
                              @endif
                              </ul>
                              <p class="list-name margin-top-botton-10">Pembelian</p>
                              <ul class="sidebar_categories">
                                <li><a href="#" class="@yield('pending_pay')">Menunggu Pembayaran</a></li>
                                <li><a href="{{ url('/transaksisaya') }}" class="@yield('daftar_trx')">Transaksi Saya
                                  @if(\App\Orders::where('user_id', \Auth::user()->id)->where('payment_status','!==','done')->count() == 1)
                                  <span class="badge badge-primary">{{count(\App\Orders::where('user_id', \Auth::user()->id)->where('payment_status', '!=', 'done')->get())}}</span>
                                  @endif
                                  </a>
                                </li>
                              </ul>
                              <p class="list-name margin-top-botton-10">Profile Saya</p>
                              <ul class="sidebar_categories">
                                <li><a href="{{ url('/biodata') }}" class="@yield('biodata')">Biodata Diri</a></li>
                                <li><a href="{{ url('/alamat') }}" class="@yield('alamat')">Alamat</a></li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="row col-md-9">
                <h3 style="padding: 35px 0px 0px 0px;color:#727577;font-weight:400">@yield('name_div')</h3>
                @yield('content_div')
                <!-- <div class="ticker css-1es387d">
                  <h4>test</h4>
                </div>
                <div class="cart_items" style="width:100%">
                  <ul class="cart_list">
                    <li class="cart_item clearfix cart_padding">
                      @yield('content_div')
                    </li>
                  </ul>
                </div> -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
@endsection