routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('/products', 'ProductsController');
Route::get('/testpro', function () {
   return view('frontend.cart.checkout');
});
Route::get('/monitorh2h', function () {
   return view('frontend.include.komodo');
});
Route::get('/invoice-info', function () {
   return view('frontend.transaction.invoice_info');
});
Route::get('/ask/{id}', function ($id) {
   return view('frontend.discussion',compact('id'));
});
Route::get('/stats', 'BackendController@getStats');
Route::get('/maintenance', function () {
   return view('maintenance');
});
// Auth::routes();
Route::resource('category', 'CategoryController', [
    'except' => ['show'],
    'names' => 'admin.category'
  ]);
Route::any('/getongkir', 'FrontendController@ongkir');
Route::get('/getCity', 'FrontendController@getCity');
Route::get('/getDistrict', 'FrontendController@getDistrict');
Route::post('/addVideo', 'ProductsController@uploadVideo')->name('products.add.video');
//Route::get('/home', 'HomeController@index');
Route::get('/empty-cart/{id}', 'CartController@destroy');
/* Frontend part of the shop */
Route::get('/', 'FrontendController@home');
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
 Route::get('/{provider}/callback', 'Auth\AuthController@handleProviderCallback');
Route::get('/home', 'FrontendController@home');
Route::get('/collection', 'FrontendController@collection')->name('frontend.collection');
//Route::get('/collection', 'FrontendController@collection');
Route::get('/topbrands', 'FrontendController@topbrands');
//Route::get('/cart', 'FrontendController@cart');
Route::get('/contact', 'FrontendController@contact');
Route::post('/attempt', 'FrontendController@attempt');
Route::post('/postDiscuss', 'FrontendController@storeDiscuss');
Route::post('/postQuestion', 'FrontendController@storeQuestion');
Route::get('/filter', 'FrontendController@filter');
Route::get('/login', 'FrontendController@login');
Route::get('/signin', 'FrontendController@signin');
Route::get('/signup', 'FrontendController@signup');
Route::get('/vendor-signup', 'FrontendController@vendorSignup');
Route::post('/registration', 'FrontendController@process_vendorSignup');
Route::get('/user/activation/{token}', 'Auth\RegisterController@userActivation');
Route::post('/process_signin', 'FrontendController@create');
Route::post('/search', 'FrontendController@search')->name('frontend.search');
Route::get('/details/{id}', 'FrontendController@details')->name('frontend.detail');
// Route::get('/category/{id}', 'FrontendController@show')->name('collection.show');
Route::get('/category/{id}', 'FrontendController@subproduct')->name('collection.subproduct');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/buynow/{id}', 'CartController@buynow')->name('cart.buy');

Route::get('shop/{id}', 'MerchantController@detail')->name('merchant.detail');

Route::resource('/cart', 'CartController');
Route::any('/update/qty', 'CartController@updateQty')->name('update.qty');
Route::resource('/address', 'AddressController');
Route::get('/checkout', 'CheckoutController@checkout')->name('frontend.checkout');
//Route::get('/checkout', 'CheckoutController@step1');


Route::get('/viewcheckout', 'FrontendController@checkout');



Route::post('/checkout', 'CheckoutController@checkout')->name('checkout');
//Route::get('/checkout', 'CheckoutController@step1');

Route::get('/snap', 'SnapController@snap');
Route::get('/delete/{id}', 'CartController@destroy');
Route::post('/snaptoken', 'SnapController@token');
Route::post('/snapfinish', 'SnapController@finish');

Route::get('/ivoucher', 'FrontendController@ivoucher')->name('frontend.ivoucher');
Route::get('/tracking', 'FrontendController@tracking')->name('frontend.tracking');

Route::group(['middleware' => 'auth'], function () {

    Route::get('shipping-info', 'CheckoutController@shipping')->name('checkout.shipping');
    Route::get('/payment', 'CheckoutController@payment')->name('checkout.payment');
    Route::post('/store-payment', 'CheckoutController@storePayment')->name('payment.store');

    Route::get('/biodata', 'FrontendController@biodata')->name('frontend.biodata');
    Route::get('/penjualan', 'FrontendController@penjualan')->name('frontend.penjualan');
    Route::get('/pembelian', 'TransactionController@pembelian')->name('frontend.pembelian');
    Route::get('/pembelian/{mode}', 'TransactionController@pembelian')->name('frontend.pembelian');
    Route::get('/my/sales', 'TransactionController@mySales')->name('frontend.mySales');
    Route::get('/list/sales/{id}', 'TransactionController@sales')->name('frontend.salesConfirmation');
    Route::post('/update/profile', 'FrontendController@profile')->name('frontend.profile');
    Route::get('/alamat', 'AddressController@alamat')->name('frontend.alamat');
    Route::post('/alamat/detail', 'AddressController@alamatDetail')->name('address.alamatDetail');
    Route::get('/alamat/delete/{id}', 'AddressController@delete')->name('address.delete');
    Route::post('/store', 'AddressController@store')->name('address.store');
    Route::post('/alamat/update', 'AddressController@update')->name('address.update');
    Route::post('/alamat/delete/{id}', 'AddressController@destroy')->name('address.destroy');
    Route::get('/discussion', 'FrontendController@discussion')->name('frontend.diskusi');
    Route::get('/discussion/{id}', 'FrontendController@discussionAkun')->name('frontend.akun');

    Route::get('/create/merchant', 'FrontendController@create_merchant')->name('frontend.create_merchant');
    Route::get('/create/step', 'FrontendController@cretae_step')->name('frontend.step');
    Route::post('/add/merchant', 'MerchantController@create')->name('merchant.add');
    Route::post('/add/merchant/step', 'MerchantController@createStep')->name('merchant.step');
    Route::get('/my/merchant/{id}', 'FrontendController@myMerchant')->name('merchant.my');
    Route::post('/merchant/{id}/edit', 'MerchantController@edit')->name('merchant.edit');
    Route::get('/shop/update/{id}', 'FrontendController@merchantUpdate')->name('merchant.update');
    Route::get('/merchant/detail', 'FrontendController@merchantDetail')->name('merchant.detail');
    Route::get('/merchant/confirmation/resi', 'FrontendController@merchantConfirmationResi')->name('merchant.confirmation');


    Route::get('/trx/sales', 'OrdersController@trxSales')->name('sales.trx');
    Route::get('/acceptOrder', 'TransactionController@transactionUpdate');
    Route::get('/denyOrder', 'TransactionController@transactionUpdate');

    //products
    Route::get('/products/add/image', 'FrontendController@productAddImage')->name('product.image');
    Route::get('/products/add/video', 'FrontendController@productAddVid')->name('product.video');
    Route::get('/products/edit/video', 'FrontendController@productEdit')->name('product.edit_video');
    Route::get('/products/choose', 'FrontendController@chooseMethod')->name('product.choose');
    Route::post('/reset/password', 'FrontendController@resetPassword')->name('profile.reset');
    Route::post('/address/change', 'AddressController@addressChange')->name('address.change');

    //my transaction
    Route::get('/trx/invoice', 'TransactionController@trxMetode');
    Route::get('/order/detail/{id}', 'OrdersController@orderDetail');
    Route::get('/trx/paymentguide', 'TransactionController@trxGuide');
    Route::any('/getguide/{id}', 'FrontendController@getGuide')->name('get.guide');
    Route::any('/trx/detail', 'TransactionController@trxDetail')->name('trx.detail');
    Route::any('/trx/detail/product', 'TransactionController@trxDetailProduct')->name('trx.detailProduct');
//    Route::get('logout', 'BackendController@getLogout')->name('frontend.signin');

    Route::get('/reservasi', 'FrontendController@reservasi');
});


    /* Backend part of the shop */
Route::get('/admin', 'BackendController@admin');


/* Admin resource controller */
Route::resource('/categories', 'CategoryController');
Route::resource('/brands', 'BrandsController');
Route::resource('/products', 'ProductsController');

Route::get('/merchant/', 'MerchantController@getMerchant');
Route::get('/merchant/{id}', 'MerchantController@detailAssigment')->name('admin.merchant.detail');
Route::post('/approveMerchant', 'MerchantController@approveShop');
Route::post('toggledeliver/{orderId}', 'OrdersController@toggledeliver')->name('toggle.deliver');
Route::resource('/attribute', 'AttributeController');
Route::resource('/attribute_set', 'AttributeSetController');
Route::get('menu/sort/{type}', 'MenuController@sort_form')->name('admin.menu.sort_form');
  Route::post('menu/sort/{type}', 'MenuController@sort')->name('admin.menu.sort');
  Route::resource('menu', 'MenuController', [
    'names' => 'admin.menu'
  ]);
Route::delete('page/bulkdelete', 'PageController@bulkdelete')->name('admin.page.bulkdelete');
  Route::get('page/search/{query?}', 'PageController@search')->name('admin.page.search');
  Route::resource('page', 'PageController', [
    'names' => 'admin.page'
  ]);
  Route::get('get_parent_menu.json', 'MenuController@parent_menu')->name('admin.menu.parent.json');
  Route::get('get_child_menu.json', 'MenuController@child_menu')->name('admin.menu.child.json');
  Route::get('get_type_menu.json', 'MenuController@type')->name('admin.menu.type');


Route::get('/users/{type?}', [
    'uses' => 'UsersController@index',
    'as' => 'users',
    'middleware' => 'roles',
    'roles' => ['Admin']
    ]);
Route::get('/manage_users', [
    'uses' => 'UsersController@manage_users',
    'as' => 'manage_users',
    'middleware' => 'roles',

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    //
    protected $table  = 'products';
    protected $primarykey = 'id';
    protected $fillable = ['name','price','qty','category_id','brand_id','image','shop_id', 'condition', 'insurance', 'weight', 'discount', 'description', 'slug', 'is_artist', 'url'];


    public function brand() {

        return $this->belongsTo('App\Brands');
    }
    public function category() {

        return $this->belongsTo('App\Category','category_id','id_category');
    }
    
    public function shop() {

        return $this->belongsTo('App\Shop');
    }

//    public function priceToCents()
//    {
//        return $this->price * 100;
//    }

}

resources/views/frontend/product/add_product_video.blade.php
@section('title')
hariBelanja - Upload Jasa
@endsection


@section('product_add')
hover-active
@endsection

@section('name_div')
  Tambah Produk
@endsection

@extends('frontend.layouts.layout_profile')

@section('css')
<style>
  /* BUTTON checked */
  .containerbtn {
      display: block;
      position: relative;
      padding-left: 35px;
      margin-bottom: 12px;
      cursor: pointer;
      font-size: 22px;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    /* Hide the browser's default radio button */
    .containerbtn input {
      position: absolute;
      opacity: 0;
      cursor: pointer;
    }

    /* Create a custom radio button */
    .checkmark {
      position: absolute;
      top: 7px;
      left: 0;
      height: 25px;
      width: 25px;
      background-color: #eee;
      border-radius: 50%;
    }

    /* On mouse-over, add a grey background color */
    .containerbtn:hover input ~ .checkmark {
      background-color: #ccc;
    }

    /* When the radio button is checked, add a blue background */
    .containerbtn input:checked ~ .checkmark {
      background-color: #2196F3;
    }

    /* Create the indicator (the dot/circle - hidden when not checked) */
    .checkmark:after {
      content: "";
      position: absolute;
      display: none;
    }

    /* Show the indicator (dot/circle) when checked */
    .containerbtn input:checked ~ .checkmark:after {
      display: block;
    }

    /* Style the indicator (dot/circle) */
    .containerbtn .checkmark:after {
     	top: 9px;
    	left: 9px;
    	width: 8px;
    	height: 8px;
    	border-radius: 50%;
    	background: white;
    }
    .hover-active{
      color:black;
    }
  </style>

  <style>
    .ticker{
      display: table;
      box-sizing: border-box;
      position: relative;
      background-color: rgba(14, 140, 228, 0.07);
      width: 100%;
      border-width: 1px;
      border-style: solid;
      border-image: initial;
      border-radius: 8px;
      overflow: hidden;
      border-color: rgb(14, 140, 228);
    }
    .css-1es387d::before {
        content: "";
        display: inline-block;
        position: absolute;
        height: 100%;
        top: 0px;
        left: 0px;
        border-left: 3px solid;
        border-color: rgb(14, 140, 228)
    }
    .padding-ticker{
      padding: 10px 10px 2px 25px;
    }
    .select{
      margin: 0px;
      color: #727577 !important;
    }
    .btn-foto {
        text-align: center;
        position: relative;
        overflow: hidden;
    }
    .btn-foto input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        cursor: inherit;
        display: block;
    }
    .span-jasa{
      margin-left: 10px;
      font-size: 15px;
    }
    .form-control {
      color: #727577 !important;
      font-size: 15px !important;
      padding: 6px 12px 6px 12px !important;
    }
  progress, progress[role] {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border: none;
    background-size: auto;
    height: 20px;
    width: 100%;
  }

  .bar::-webkit-progress-value {
    background: #0e8ce4;
  }

  label {
    font-weight: 400 !important;
    }

  select.form-control:not([size]):not([multiple]) {
      height: auto!important;
  }
  </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
@endsection

@section('content_div')
  <div class="ticker css-1es387d">
    <div class="padding-ticker" style="font-size: 12px;">
      <p>Sebelum menambahkan produk/jasa, pastikan produk/jasa tersebut sudah sesuai dengan syarat dan ketentuan hariBelanja. Semua produk/jasa yang melanggar syarat dan ketentuan akan dinon-aktifkan oleh tim kami.</p>
    </div>
  </div>
  <div class="cart_items" style="width:100%;margin-top:10px;">
    <ul class="cart_list">
      <li class="cart_item clearfix cart_padding">
        <div class="row" style="padding-right: 15px;padding-left: 15px; display:block;">
          <form action="{{ route('products.add.video')}}" method="POST"  form-type="upload" enctype="multipart/form-data">


            <div class="row select">
              <div class="col-md-12">
                <div class="col-md-12 order_total_content" style="padding-top:20px;">
                  {{ @csrf_field()}}
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Nama Product</label>
                     <div class="col-sm-10">
                       <input type="text" name="nama" class="form-control" id="inputEmail3" placeholder="Nama Product">
                     </div>
                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Url Video produk</label>
                     <div class="col-sm-10">
                       <input type="text" name="url" class="form-control" id="inputEmail3" placeholder="contoh:https://www.youtube.com/watch?v=JGHPDG9xyok">
                     </div>
                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Deskripsi <span data-toggle="tooltip" data-placement="right" title="Deskripsikan jasa yang diberikan. Durasi jasa dan jadwal reservasi melalui kontak yang bisa dihubungi"><i class="fas fa-info-circle"></i></span></label>
                     <div class="col-sm-10">
                       <textarea type="text" name="description" class="form-control" id="inputEmail3" placeholder="Deskripsi barang"></textarea>
                     </div>
                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Kategori</label>
                     <div class="col-sm-4">
                       <select name="category" class="form-control select" id="category">
                         <option value="">Kategori</option>
                         @foreach(App\Category::where('id_parent', "")->get() as $key => $value)
                         <option class="{{$value->id_category}}" value="{{$value->id_category}}">{{$value->title}}</option>
                         @endforeach
                       </select>

                     </div>

                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Harga</label>
                     <div class="col-sm-10">
                       <input name="harga" type="text" class="form-control" id="inputEmail3" placeholder="Harga">
                     </div>
                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Diskon</label>
                     <div class="col-sm-10">
                       <input type="number" name="discount" class="form-control select" value="0" id="inputEmail3" placeholder="Diskon Barang">
                     </div>
                   </div>
                </div>
              </div>
            </div>
            <div class="order_total_content text-md-right margin-top-15" style="padding-right: 15px;padding-left: 15px;">
              <div class="contact_form_button">
                <input type="submit" class="button cart_button_checkout" value="Simpan">
              </div>
            </div>
            </form>
          </div>
        </li>
      </ul>
    </div>
@endsection
@section('someJS')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-chained/1.0.1/jquery.chained.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script type="text/javascript">
 $(document).ready(function(){
   $('[data-toggle="tooltip"]').tooltip();
   var msg = "{{ Session::has('msg') }}";
   if(msg == 1){
     var message = "{{ Session::get('msg') }}";
     alert(message);
   }

      $("#subcategory").chainedTo("#category");

    // $(".upload").on('change',function(){
    //   console.log($(this).data('id'));
    //   var filereader = new FileReader();
    //   var $img=jQuery.parseHTML("<img style='width: 100%;height:128px;' src=''>");
    //   filereader.onload = function(){
    //       $img[0].src=this.result;
    //   };
    //   filereader.readAsDataURL(this.files[0]);
    //    $("#preview" + $(this).data("id")).empty();
    //   $("#preview" + $(this).data("id")).append($img);
    // });
  });
</script>
@endsection

resources/views/frontend/product/edit_product_video.blade.php
@section('title')
hariBelanja - Edit Jasa
@endsection


@section('product')
hover-active
@endsection

@section('name_div')
  Tambah Produk
@endsection

@extends('frontend.layouts.layout_profile')

@section('css')
<style>
  /* BUTTON checked */
  .containerbtn {
      display: block;
      position: relative;
      padding-left: 35px;
      margin-bottom: 12px;
      cursor: pointer;
      font-size: 22px;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    /* Hide the browser's default radio button */
    .containerbtn input {
      position: absolute;
      opacity: 0;
      cursor: pointer;
    }

    /* Create a custom radio button */
    .checkmark {
      position: absolute;
      top: 7px;
      left: 0;
      height: 25px;
      width: 25px;
      background-color: #eee;
      border-radius: 50%;
    }

    /* On mouse-over, add a grey background color */
    .containerbtn:hover input ~ .checkmark {
      background-color: #ccc;
    }

    /* When the radio button is checked, add a blue background */
    .containerbtn input:checked ~ .checkmark {
      background-color: #2196F3;
    }

    /* Create the indicator (the dot/circle - hidden when not checked) */
    .checkmark:after {
      content: "";
      position: absolute;
      display: none;
    }

    /* Show the indicator (dot/circle) when checked */
    .containerbtn input:checked ~ .checkmark:after {
      display: block;
    }

    /* Style the indicator (dot/circle) */
    .containerbtn .checkmark:after {
     	top: 9px;
    	left: 9px;
    	width: 8px;
    	height: 8px;
    	border-radius: 50%;
    	background: white;
    }
    .hover-active{
      color:black;
    }
  </style>

  <style>
    .ticker{
      display: table;
      box-sizing: border-box;
      position: relative;
      background-color: rgba(14, 140, 228, 0.07);
      width: 100%;
      border-width: 1px;
      border-style: solid;
      border-image: initial;
      border-radius: 8px;
      overflow: hidden;
      border-color: rgb(14, 140, 228);
    }
    .css-1es387d::before {
        content: "";
        display: inline-block;
        position: absolute;
        height: 100%;
        top: 0px;
        left: 0px;
        border-left: 3px solid;
        border-color: rgb(14, 140, 228)
    }
    .padding-ticker{
      padding: 10px 10px 2px 25px;
    }
    .select{
      margin: 0px;
      color: #727577 !important;
    }
    .btn-foto {
        text-align: center;
        position: relative;
        overflow: hidden;
    }
    .btn-foto input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        cursor: inherit;
        display: block;
    }
    .span-jasa{
      margin-left: 10px;
      font-size: 15px;
    }
    .form-control {
      color: #727577 !important;
      font-size: 15px !important;
      padding: 6px 12px 6px 12px !important;
    }
  progress, progress[role] {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    border: none;
    background-size: auto;
    height: 20px;
    width: 100%;
  }

  .bar::-webkit-progress-value {
    background: #0e8ce4;
  }

  label {
    font-weight: 400 !important;
    }

  select.form-control:not([size]):not([multiple]) {
      height: auto!important;
  }
  </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
@endsection

@section('content_div')
  <div class="ticker css-1es387d">
    <div class="padding-ticker" style="font-size: 12px;">
      <p>Sebelum menambahkan produk/jasa, pastikan produk/jasa tersebut sudah sesuai dengan syarat dan ketentuan hariBelanja. Semua produk/jasa yang melanggar syarat dan ketentuan akan dinon-aktifkan oleh tim kami.</p>
    </div>
  </div>
  <div class="cart_items" style="width:100%;margin-top:10px;">
    <ul class="cart_list">
      <li class="cart_item clearfix cart_padding">
        <div class="row " style="padding-right: 15px;padding-left: 15px; display:block;">
          <form action="{{ route('products.update', $product_edit->id) }}" method="POST"  form-type="upload" enctype="multipart/form-data">
            <input hidden name="id" value="{{ $product_edit->id }}">
            <input type="hidden" name="_method" value="PUT">
            <div class="row select">
              <div class="col-md-12">
                <div class="col-md-12 order_total_content" style="padding-top:20px;">
                  {{ @csrf_field()}}
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Nama Product</label>
                     <div class="col-sm-10">
                       <input type="text" name="nama" class="form-control" id="inputEmail3" value="{{ $product_edit->name }}">
                     </div>
                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Url Video produk</label>
                     <div class="col-sm-10">
                       <input type="text" name="url" class="form-control" id="inputEmail3" value="https://youtube.com/watch?v={{ $product_edit->url }}">
                     </div>
                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Deskripsi <span data-toggle="tooltip" data-placement="right" title="Deskripsikan jasa yang diberikan. Durasi jasa dan jadwal reservasi melalui kontak yang bisa dihubungi"><i class="fas fa-info-circle"></i></span></label>
                     <div class="col-sm-10">
                       <textarea type="text" name="description" class="form-control" id="inputEmail3">{{ $product_edit->description }}</textarea>
                     </div>
                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Kategori</label>
                     <div class="col-sm-4">
                       <select name="category_id" class="form-control select" id="category">
                         <option value="">Kategori</option>
                         @foreach(App\Category::where('id_parent', "")->get() as $key => $value)
                         <option class="{{$value->id_category}}" value="{{$value->id_category}}" {{ $product_edit->category_id == $value->id_category ? 'selected' : '' }}>{{$value->title}}</option>
                         @endforeach
                       </select>

                     </div>

                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Harga</label>
                     <div class="col-sm-10">
                       <input name="harga" type="text" class="form-control" id="inputEmail3" value="{{ $product_edit->price }}">
                     </div>
                   </div>
                   <div class="form-group row">
                     <label for="inputEmail3" class="col-sm-2 col-form-label">Diskon</label>
                     <div class="col-sm-10">
                       <input type="number" name="discount" class="form-control select" value="0" id="inputEmail3" value="{{ $product_edit->discount ? $product_edit->discount : 0}}">
                     </div>
                   </div>
                </div>
              </div>
            </div>
            <div class="order_total_content text-md-right margin-top-15" style="padding-right: 15px;padding-left: 15px;">
              <div class="contact_form_button">
                <input type="submit" class="button cart_button_checkout" value="Simpan">
              </div>
            </div>
            </form>
          </div>
        </li>
      </ul>
    </div>
@endsection
@section('someJS')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-chained/1.0.1/jquery.chained.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script type="text/javascript">
 $(document).ready(function(){
   $('[data-toggle="tooltip"]').tooltip();
   var msg = "{{ Session::has('msg') }}";
   if(msg == 1){
     var message = "{{ Session::get('msg') }}";
     alert(message);
   }

      $("#subcategory").chainedTo("#category");

    // $(".upload").on('change',function(){
    //   console.log($(this).data('id'));
    //   var filereader = new FileReader();
    //   var $img=jQuery.parseHTML("<img style='width: 100%;height:128px;' src=''>");
    //   filereader.onload = function(){
    //       $img[0].src=this.result;
    //   };
    //   filereader.readAsDataURL(this.files[0]);
    //    $("#preview" + $(this).data("id")).empty();
    //   $("#preview" + $(this).data("id")).append($img);
    // });
  });
</script>
@endsection