routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('/products', 'ProductsController');
Route::get('/testpro', function () {
   return view('frontend.cart.checkout');
});
Route::get('/monitorh2h', function () {
   return view('frontend.include.komodo');
});
Route::get('/invoice-info', function () {
   return view('frontend.transaction.invoice_info');
});
Route::get('/ask/{id}', function ($id) {
   return view('frontend.discussion',compact('id'));
});
Route::get('/stats', 'BackendController@getStats');
Route::get('/maintenance', function () {
   return view('maintenance');
});
// Auth::routes();
Route::resource('category', 'CategoryController', [
    'except' => ['show'],
    'names' => 'admin.category'
  ]);
Route::any('/getongkir', 'FrontendController@ongkir');
Route::get('/getCity', 'FrontendController@getCity');
Route::get('/getDistrict', 'FrontendController@getDistrict');
Route::post('/addVideo', 'ProductsController@uploadVideo')->name('products.add.video');
//Route::get('/home', 'HomeController@index');
Route::get('/empty-cart/{id}', 'CartController@destroy');
/* Frontend part of the shop */
Route::get('/', 'FrontendController@home');
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider');
 Route::get('/{provider}/callback', 'Auth\AuthController@handleProviderCallback');
Route::get('/home', 'FrontendController@home');
Route::get('/collection', 'FrontendController@collection')->name('frontend.collection');
//Route::get('/collection', 'FrontendController@collection');
Route::get('/topbrands', 'FrontendController@topbrands');
//Route::get('/cart', 'FrontendController@cart');
Route::get('/contact', 'FrontendController@contact');
Route::post('/attempt', 'FrontendController@attempt');
Route::post('/postDiscuss', 'FrontendController@storeDiscuss');
Route::post('/postQuestion', 'FrontendController@storeQuestion');
Route::get('/filter', 'FrontendController@filter');
Route::get('/login', 'FrontendController@login');
Route::get('/signin', 'FrontendController@signin');
Route::get('/signup', 'FrontendController@signup');
Route::get('/vendor-signup', 'FrontendController@vendorSignup');
Route::post('/registration', 'FrontendController@process_vendorSignup');
Route::get('/user/activation/{token}', 'Auth\RegisterController@userActivation');
Route::post('/process_signin', 'FrontendController@create');
Route::post('/search', 'FrontendController@search')->name('frontend.search');
Route::get('/details/{id}', 'FrontendController@details')->name('frontend.detail');
// Route::get('/category/{id}', 'FrontendController@show')->name('collection.show');
Route::get('/category/{id}', 'FrontendController@subproduct')->name('collection.subproduct');
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/buynow/{id}', 'CartController@buynow')->name('cart.buy');

Route::get('shop/{id}', 'MerchantController@detail')->name('merchant.detail');

Route::resource('/cart', 'CartController');
Route::any('/update/qty', 'CartController@updateQty')->name('update.qty');
Route::resource('/address', 'AddressController');
Route::get('/checkout', 'CheckoutController@checkout')->name('frontend.checkout');
//Route::get('/checkout', 'CheckoutController@step1');


Route::get('/viewcheckout', 'FrontendController@checkout');



Route::post('/checkout', 'CheckoutController@checkout')->name('checkout');
//Route::get('/checkout', 'CheckoutController@step1');

Route::get('/snap', 'SnapController@snap');
Route::get('/delete/{id}', 'CartController@destroy');
Route::post('/snaptoken', 'SnapController@token');
Route::post('/snapfinish', 'SnapController@finish');

Route::get('/ivoucher', 'FrontendController@ivoucher')->name('frontend.ivoucher');
Route::get('/tracking', 'FrontendController@tracking')->name('frontend.tracking');

Route::group(['middleware' => 'auth'], function () {

    Route::get('shipping-info', 'CheckoutController@shipping')->name('checkout.shipping');
    Route::get('/payment', 'CheckoutController@payment')->name('checkout.payment');
    Route::post('/store-payment', 'CheckoutController@storePayment')->name('payment.store');

    Route::get('/biodata', 'FrontendController@biodata')->name('frontend.biodata');
    Route::get('/penjualan', 'FrontendController@penjualan')->name('frontend.penjualan');
    Route::get('/pembelian', 'TransactionController@pembelian')->name('frontend.pembelian');
    Route::get('/pembelian/{mode}', 'TransactionController@pembelian')->name('frontend.pembelian');
    Route::get('/my/sales', 'TransactionController@mySales')->name('frontend.mySales');
    Route::get('/list/sales/{id}', 'TransactionController@sales')->name('frontend.salesConfirmation');
    Route::post('/update/profile', 'FrontendController@profile')->name('frontend.profile');
    Route::get('/alamat', 'AddressController@alamat')->name('frontend.alamat');
    Route::post('/alamat/detail', 'AddressController@alamatDetail')->name('address.alamatDetail');
    Route::get('/alamat/delete/{id}', 'AddressController@delete')->name('address.delete');
    Route::post('/store', 'AddressController@store')->name('address.store');
    Route::post('/alamat/update', 'AddressController@update')->name('address.update');
    Route::post('/alamat/delete/{id}', 'AddressController@destroy')->name('address.destroy');
    Route::get('/discussion', 'FrontendController@discussion')->name('frontend.diskusi');
    Route::get('/discussion/{id}', 'FrontendController@discussionAkun')->name('frontend.akun');

    Route::get('/create/merchant', 'FrontendController@create_merchant')->name('frontend.create_merchant');
    Route::get('/create/step', 'FrontendController@cretae_step')->name('frontend.step');
    Route::post('/add/merchant', 'MerchantController@create')->name('merchant.add');
    Route::post('/add/merchant/step', 'MerchantController@createStep')->name('merchant.step');
    Route::get('/my/merchant/{id}', 'FrontendController@myMerchant')->name('merchant.my');
    Route::post('/merchant/{id}/edit', 'MerchantController@edit')->name('merchant.edit');
    Route::get('/shop/update/{id}', 'FrontendController@merchantUpdate')->name('merchant.update');
    Route::get('/merchant/detail', 'FrontendController@merchantDetail')->name('merchant.detail');
    Route::get('/merchant/confirmation/resi', 'FrontendController@merchantConfirmationResi')->name('merchant.confirmation');


    Route::get('/trx/sales', 'OrdersController@trxSales')->name('sales.trx');
    Route::get('/acceptOrder', 'TransactionController@transactionUpdate');
    Route::get('/denyOrder', 'TransactionController@transactionUpdate');

    //products
    Route::get('/products/add/image', 'FrontendController@productAddImage')->name('product.image');
    Route::get('/products/add/video', 'FrontendController@productAddVid')->name('product.video');
    Route::get('/products/edit/video', 'FrontendController@productEdit')->name('product.edit_video');
    Route::get('/products/choose', 'FrontendController@chooseMethod')->name('product.choose');
    Route::post('/reset/password', 'FrontendController@resetPassword')->name('profile.reset');
    Route::post('/address/change', 'AddressController@addressChange')->name('address.change');

    //my transaction
    Route::get('/trx/invoice', 'TransactionController@trxMetode');
    Route::get('/order/detail/{id}', 'OrdersController@orderDetail');
    Route::get('/trx/paymentguide', 'TransactionController@trxGuide');
    Route::any('/getguide/{id}', 'FrontendController@getGuide')->name('get.guide');
    Route::any('/trx/detail', 'TransactionController@trxDetail')->name('trx.detail');
    Route::any('/trx/detail/product', 'TransactionController@trxDetailProduct')->name('trx.detailProduct');
//    Route::get('logout', 'BackendController@getLogout')->name('frontend.signin');

    Route::get('/reservasi', 'FrontendController@reservasi');
});


    /* Backend part of the shop */
Route::get('/admin', 'BackendController@admin');


/* Admin resource controller */
Route::resource('/categories', 'CategoryController');
Route::resource('/brands', 'BrandsController');
Route::resource('/products', 'ProductsController');

Route::get('/merchant/', 'MerchantController@getMerchant');
Route::get('/merchant/{id}', 'MerchantController@detailAssigment')->name('admin.merchant.detail');
Route::post('/approveMerchant', 'MerchantController@approveShop');
Route::post('toggledeliver/{orderId}', 'OrdersController@toggledeliver')->name('toggle.deliver');
Route::resource('/attribute', 'AttributeController');
Route::resource('/attribute_set', 'AttributeSetController');
Route::get('menu/sort/{type}', 'MenuController@sort_form')->name('admin.menu.sort_form');
  Route::post('menu/sort/{type}', 'MenuController@sort')->name('admin.menu.sort');
  Route::resource('menu', 'MenuController', [
    'names' => 'admin.menu'
  ]);
Route::delete('page/bulkdelete', 'PageController@bulkdelete')->name('admin.page.bulkdelete');
  Route::get('page/search/{query?}', 'PageController@search')->name('admin.page.search');
  Route::resource('page', 'PageController', [
    'names' => 'admin.page'
  ]);
  Route::get('get_parent_menu.json', 'MenuController@parent_menu')->name('admin.menu.parent.json');
  Route::get('get_child_menu.json', 'MenuController@child_menu')->name('admin.menu.child.json');
  Route::get('get_type_menu.json', 'MenuController@type')->name('admin.menu.type');


Route::get('/users/{type?}', [
    'uses' => 'UsersController@index',
    'as' => 'users',
    'middleware' => 'roles',
    'roles' => ['Admin']
    ]);
Route::get('/manage_users', [
    'uses' => 'UsersController@manage_users',
    'as' => 'manage_users',
    'middleware' => 'roles',

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
class Category extends Model
{

    protected $table = 'category';
    protected $primaryKey = 'id_category';
    protected $fillable = [
      'title', 'slug', 'description', 'schema', 'meta_title', 'meta_description', 'meta_keyword', 'id_parent',
      'id_user'
    ];

    public function products() {

        return $this->hasMany('App\Products');
    }
    public function getParentCategoryAttribute() {
      $category = Category::where('id_category', $this->attributes['id_parent']);
      return $category;
    }
     public function getTotalProductBaseOnCategory($parent, $key)
    {
      $id_parent = Category::where('title',ucfirst(strtolower($parent)))->whereNull('id_parent')->firstOrFail()->id_category;
      $search = $key;
      $data = Products::whereHas('Category', function ($q) use($id_parent,$search ) {
          $q->whereHas('parent', function ($q) use($id_parent,$search ){
              $q->where('id_parent', $id_parent)->whereRaw("slug = ?",[$search]);
          });
      });
      return $data->count();
    }
    public function parent() {
        return $this->hasOne('App\Category', 'id_category', 'id_parent');
    }

    public function child() {
        return $this->hasMany('App\Category', 'id_parent', 'id_category');
    }

    public function user() {
      return $this->hasOne('App\User', 'id', 'id_user');
    }

    public function productCategory()
    {
        return $this->hasMany('App\MovieCategory', 'id_category', 'id_category');
    }

    public function actorKeyword()
    {
        return $this->hasMany('App\ActorKeyword', 'id_category', 'id_category');
    }

    // public function brands() {

    //     return $this->hasMany('App\Brands','category_id');
    // }
}

app/Http/Controllers/BackendController.php
<?php
namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use DB;
use App\Orders;
use App\Shop;
class BackendController extends Controller {
    //
    public function __construct() {
        $this->middleware(['auth', 'admin']);
    }

    public function admin() {
      $stats['user'] = DB::select(DB::raw("SELECT count(*) as c, DATE(created_at) as d FROM users GROUP BY DATE(users.created_at)"));
      $stats['merchant'] = DB::select(DB::raw("SELECT count(*) as c, DATE(created_at) as d FROM shop GROUP BY DATE(shop.created_at)"));
      $stats['transaction'] = DB::select(DB::raw("SELECT count(*) as c, DATE(created_at) as d FROM orders GROUP BY DATE(orders.created_at)"));
    
        $data['user'] = User::count();
        $data['transaction'] = Orders::count();
        $data['shops'] = Shop::count();
        $data['pending_approve'] = Shop::whereStatus(0)->count();
        return view('backend.dashboard', compact('data'));
    }
    public function getStats() {

        return response()->json($stats);
    }
    public function categories() {
        return view('backend.categories');
    }
    public function products() {
        return view('backend.products');
    }
    public function brands() {
        return view('backend.brands');
    }
    public function order() {
        return view('backend.order');
    }
    public function getLogout() {
        Auth::logout();
        Session::flush();
        return redirect()->route('frontend.signin');
    }
}

resources/views/backend/category/categories.blade.php
@extends('backend.includes.header')

@section('content')
  <div class="right_col" role="main">
    <div class="">
      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h3 class="pull-left">{{ $parent == null ? '' : 'Subkategori dari kategori ' .$parent->title }}</h3>
              <a href="{{ route('categories.create') }}" class="btn btn-success pull-right"><i class="fa fa-plus" aria-hidden="true"></i> Create</a>
              <div class="clearfix">
              </div>
            </div>
            <div class="x_content">
              <div class="">
                <form id="bulk-delete-form" action="" method="POST">
                  <input type="hidden" name="_method" value="DELETE">
                  <table class="table table-striped jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                          <input type="checkbox" id="check-all" class="flat">
                        </th>
                        <th class="column-title">Title </th>
                        <th class="column-title">Slug </th>
                        <!-- <th class="column-title">Total Movie(s)</th> -->
                        <th class="column-title">Modified</th>

                        <th class="column-title no-link last" style="text-align: center;width: 30%" colspan="3"><span class="nobr">Action</span>
                        </th>
                        <th class="bulk-actions" colspan="8">
                          <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <button class="badge bg-red" id="bulk-delete-button"><i class="fa fa-trash"></i></button></a>
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      @if (!count($categories))
                        <tr class="even pointer">
                          <td colspan="8">Tidak ada data</td>
                        </tr>
                      @endif
                      @foreach ($categories as $key => $category)
                        <tr class="even pointer">
                          <td class="a-center ">
                            <input type="checkbox" class="flat" name="table_records" value="{{ $category->id_category }}">
                          </td>
                          <td class=" ">{{ $category->title }}</td>
                          <td class=" ">/{{ ($category->parent_category->count()) ? $category->parent_category->first()->slug.'/' : '' }}{{ $category->slug }}</td>

                          <td class=" ">{{ $category->updated_at->diffForHumans() }}</td>
                          <td style="text-align: center;"><a href="{{ route('categories.edit', $category->id_category) }}">Edit</a></td>
                          <td style="text-align: center;"><a href="{{ route('categories.destroy', $category->id_category) }}" class="delete-menu">Delete</a></td>
                          <td  style="text-align: center;" class=" ">{!! $category->id_parent =='' ? '<a href="' . route("categories.query", $category->id_category) . '">Lihat Subkategori</a>' : '' !!}</td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </form>
              </div>
              {{ $categories->links() }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade modal-delete-menu" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title">Delete Category</h4>
        </div>
        <div class="modal-body">
          <p>Apakah kamu yakin ingin menghapus category ini?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
          <button type="button" class="btn btn-danger" id="delete-menu-modal-button" data-url=""><span class="fa fa-trash"></span> Delete Category</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade modal-bulk-delete" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title">Delete Category</h4>
        </div>
        <div class="modal-body">
          <p>Apakah kamu yakin ingin menghapus category yang ditandai?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Batal</button>
          <button type="button" class="btn btn-danger" id="bulk-delete-modal-button" data-url=""><span class="fa fa-trash"></span> Delete Category</button>
        </div>
      </div>
    </div>
  </div>
  <form id="delete-menu-form" action="" method="post">
    <input type="hidden" name="_method" value="DELETE">
  </form>
  <script type="text/javascript">
    var DELETE_SUCCESS_LINK = DELETE_MENU_SUCCESS_LINK = "{{ route('categories.index') }}";
  </script>
@endsection

resources/views/backend/category/create-category.blade.php
@extends('backend.includes.header')

@section('content')
  <div class="right_col" role="main">
    <div class="">
      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h3>Create new category</h3>
              <div class="clearfix">
              </div>
            </div>
            <form id="create_category_form" action="{{ route('categories.store') }}" method="post">
              <div class="x_content">
                <div class="table-responsive">
                  <div class="col-md-9">
                    <div class="col-md-6">
                      <h4>Title</h4>
                      <input type="text" class="form-control" placeholder="Title" name="title">
                    </div>
                    <div class="col-md-6">
                      <h4>Parent Category</h4>
                      <select name="id_parent" class="select2_single form-control" tabindex="-1">
                        <option value=""></option>
                        @foreach ($categories as $key => $category)
                          <option value="{{ $category->id_category }}">{{ $category->title }}</option>
                        @endforeach
                      </select>
                    </div>
                    {{ csrf_field() }}
                    <div class="col-md-12 col-sm-12 col-xs-12" style="padding-top:25px">
                      <h2>Description</h2>
                      <div class="x_content">
                        <div id="alerts"></div>
                        <textarea class="content" id="content" name="description"></textarea>
                      </div>
                    </div>

                  </div>
                  <div class="col-md-3">
                    <div class="container x_panel" style="background-color:#d9edf7" >
                      <div class="btn-group " style="width:100%">
                        <p>Schema</p>
                        <select class="form-control btn-primary" name="schema">
                          <option>CollectionPage</option>
                        </select>

                      </div><br><br>
                      <div class="">
                        <p>Meta Title</p>
                        <input type="text" class="form-control" placeholder="Meta Title" name="meta_title">
                      </div><br>
                      <div class="">
                        <p>Meta Description</p>
                        <textarea id="textarea.tinymce" class="form-control" rows="3" placeholder="Meta Description" name="meta_description"></textarea>
                      </div><br>
                      <div class="">
                        <p>Meta Keywords</p>
                        <input type="text" class="form-control" placeholder="Meta Keywords" name="meta_keyword">
                      </div><br>
                      <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <button class="btn btn-primary" type="reset">Reset</button>
                          <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    var CREATE_CATEGORY_SUCCESS_LINK = "{{ route('categories.index') }}";
  </script>
@endsection
 @section('script')
  <script type="text/javascript">
    $(function() {
   $('textarea.tinymce').tinymce({
    ...
   });
});

  </script>
    @endsection

resources/views/backend/category/edit-category.blade.php
@extends('backend.includes.header')

@section('content')
  <div class="right_col" role="main">
    <div class="">
      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h3>Edit category</h3>
              <div class="clearfix">
              </div>
            </div>
            <form id="create_category_form" action="{{ route('admin.category.update', $category->id_category) }}" method="post">
              <input type="hidden" name="_method" value="PATCH">
              <div class="x_content">
                <div class="table-responsive">
                  <div class="col-md-9">
                    <div class="col-md-6">
                      <h4>Title</h4>
                      <input type="text" class="form-control" placeholder="Title" name="title" value="{{ $category->title }}">
                    </div>
                    <div class="col-md-6">
                      <h4>Parent Category</h4>
                      <select name="id_parent" class="select2_single form-control" tabindex="-1">
                        <option value=""></option>
                        @foreach ($categories as $key => $cat)
                          <option value="{{ $cat->id_category }}"{{ ($cat->id_category == $category->id_parent) ? ' selected' : '' }}>{{ $cat->title }}</option>
                        @endforeach
                      </select>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12" style="padding-top:25px">
                      <h2>Description</h2>
                      <div class="x_content">
                        <div id="alerts"></div>
                        <textarea class="content" id="content" name="description">{{ $category->description }}</textarea>
                      </div>
                    </div>

                  </div>
                  <div class="col-md-3">
                    <div class="container x_panel" style="background-color:#d9edf7" >
                      <div class="btn-group " style="width:100%">
                        <p>Schema</p>
                        <select class="form-control btn-primary" name="schema">
                          <option>CollectionPage</option>
                        </select>

                      </div><br><br>
                      <div class="">
                        <p>Meta Title</p>
                        <input type="text" class="form-control" placeholder="Meta Title" name="meta_title" value="{{ $category->meta_title }}">
                      </div><br>
                      <div class="">
                        <p>Meta Description</p>
                        <textarea class="form-control" rows="3" placeholder="Meta Description" name="meta_description">{{ $category->meta_description }}</textarea>
                      </div><br>
                      <div class="">
                        <p>Meta Keywords</p>
                        <input type="text" class="form-control" placeholder="Meta Keywords" name="meta_keyword" value="{{ $category->meta_keyword }}">
                      </div><br>
                      <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                          <button class="btn btn-primary" type="reset">Reset</button>
                          <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    var CREATE_CATEGORY_SUCCESS_LINK = "{{ route('admin.category.index') }}";
  </script>
@endsection